package org.fourstack.business.enums;

import lombok.Getter;

@Getter
public enum States {
    ANDAMAN_AND_NICOBAR_ISLANDS("ANDAMAN AND NICOBAR ISLANDS"),
    CHANDIGARH("CHANDIGARH"),
    DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU("DADRA AND NAGAR HAVELI AND DAMAN AND DIU"),
    DELHI("DELHI"),JAMMU_AND_KASHMIR("JAMMU AND KASHMIR"),
    LADAKH("LADAKH"),LAKSHADWEEP("LAKSHADWEEP"),PUDUCHERRY("PUDUCHERRY"),
    ANDHRA_PRADESH("ANDHRA PRADESH"),
    ARUNACHAL_PRADESH("ARUNACHAL PRADESH"),ASSAM("ASSAM"),BIHAR("BIHAR"),
    CHHATTISGARH("CHHATTISGARH"),GOA("GOA"),GUJARAT("GUJARAT"),HARYANA("HARYANA"),
    HIMACHAL_PRADESH("HIMACHAL PRADESH"),JHARKHAND("JHARKHAND"),KARNATAKA("KARNATAKA"),
    KERALA("KERALA"),MADHYA_PRADESH("MADHYA PRADESH"),MAHARASHTRA("MAHARASHTRA"),
    MANIPUR("MANIPUR"),MEGHALAYA("MEGHALAYA"),MIZORAM("MIZORAM"),NAGALAND("NAGALAND"),
    ODISHA("ODISHA"),PUNJAB("PUNJAB"),RAJASTHAN("RAJASTHAN"),SIKKIM("SIKKIM"),
    TAMIL_NADU("TAMIL NADU"),TELANGANA("TELANGANA"),TRIPURA("TRIPURA"),
    UTTAR_PRADESH("UTTAR PRADESH"),UTTARAKHAND("UTTARAKHAND"),WEST_BENGAL("WEST BENGAL");

    States(String value) {
        this.value = value;
    }

    private final String value;
}
